services:
  sql-server:
    image: mcr.microsoft.com/mssql/server
    environment:
      MSSQL_SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql

  isthmus.api:
    image: felpsgus/isthmus.api
    depends_on:
      - sql-server
    ports:
      - "8080:8080"
    environment:
      ENVIRONMENT_CONNECTION: "Server=sql-server;Database=Isthmus;User Id=sa;Password=Password123;TrustServerCertificate=True"

volumes:
  sql-data:
